USE [master]
GO

/****** Object:  Database [Mede]    Script Date: 9/10/2015 4:17:26 PM ******/
CREATE DATABASE [Mede] ON  PRIMARY 
( NAME = N'Mede', FILENAME = N'E:\sql_db\Mede.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Mede_log', FILENAME = N'F:\sql_db\Mede_log.LDF' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Mede] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mede].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Mede] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Mede] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Mede] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Mede] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Mede] SET ARITHABORT OFF 
GO

ALTER DATABASE [Mede] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Mede] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Mede] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Mede] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Mede] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Mede] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Mede] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Mede] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Mede] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Mede] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Mede] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Mede] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Mede] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Mede] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Mede] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Mede] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Mede] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Mede] SET RECOVERY FULL 
GO

ALTER DATABASE [Mede] SET  MULTI_USER 
GO

ALTER DATABASE [Mede] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Mede] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Mede] SET  READ_WRITE 
GO


--==============
-- add user
--==============
USE [Mede]
GO
/****** Object:  User [hemiuser]    Script Date: 9/10/2015 4:19:35 PM ******/
CREATE USER [hemiuser] FOR LOGIN [hemiuser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [hemiuser]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [hemiuser]
GO